// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package generic

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type Endpoint struct {
	pulumi.CustomResourceState

	// JSON-encoded data to write.
	DataJson pulumi.StringOutput `pulumi:"dataJson"`
	// Don't attempt to delete the path from Vault if true
	DisableDelete pulumi.BoolPtrOutput `pulumi:"disableDelete"`
	// Don't attempt to read the path from Vault if true; drift won't be detected
	DisableRead pulumi.BoolPtrOutput `pulumi:"disableRead"`
	// When reading, disregard fields not present in data_json
	IgnoreAbsentFields pulumi.BoolPtrOutput `pulumi:"ignoreAbsentFields"`
	// Full path where to the endpoint that will be written
	Path pulumi.StringOutput `pulumi:"path"`
	// Map of strings returned by write operation
	WriteData pulumi.StringMapOutput `pulumi:"writeData"`
	// JSON data returned by write operation
	WriteDataJson pulumi.StringOutput `pulumi:"writeDataJson"`
	// Top-level fields returned by write to persist in state
	WriteFields pulumi.StringArrayOutput `pulumi:"writeFields"`
}

// NewEndpoint registers a new resource with the given unique name, arguments, and options.
func NewEndpoint(ctx *pulumi.Context,
	name string, args *EndpointArgs, opts ...pulumi.ResourceOption) (*Endpoint, error) {
	if args == nil || args.DataJson == nil {
		return nil, errors.New("missing required argument 'DataJson'")
	}
	if args == nil || args.Path == nil {
		return nil, errors.New("missing required argument 'Path'")
	}
	if args == nil {
		args = &EndpointArgs{}
	}
	var resource Endpoint
	err := ctx.RegisterResource("vault:generic/endpoint:Endpoint", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEndpoint gets an existing Endpoint resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEndpoint(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EndpointState, opts ...pulumi.ResourceOption) (*Endpoint, error) {
	var resource Endpoint
	err := ctx.ReadResource("vault:generic/endpoint:Endpoint", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Endpoint resources.
type endpointState struct {
	// JSON-encoded data to write.
	DataJson *string `pulumi:"dataJson"`
	// Don't attempt to delete the path from Vault if true
	DisableDelete *bool `pulumi:"disableDelete"`
	// Don't attempt to read the path from Vault if true; drift won't be detected
	DisableRead *bool `pulumi:"disableRead"`
	// When reading, disregard fields not present in data_json
	IgnoreAbsentFields *bool `pulumi:"ignoreAbsentFields"`
	// Full path where to the endpoint that will be written
	Path *string `pulumi:"path"`
	// Map of strings returned by write operation
	WriteData map[string]string `pulumi:"writeData"`
	// JSON data returned by write operation
	WriteDataJson *string `pulumi:"writeDataJson"`
	// Top-level fields returned by write to persist in state
	WriteFields []string `pulumi:"writeFields"`
}

type EndpointState struct {
	// JSON-encoded data to write.
	DataJson pulumi.StringPtrInput
	// Don't attempt to delete the path from Vault if true
	DisableDelete pulumi.BoolPtrInput
	// Don't attempt to read the path from Vault if true; drift won't be detected
	DisableRead pulumi.BoolPtrInput
	// When reading, disregard fields not present in data_json
	IgnoreAbsentFields pulumi.BoolPtrInput
	// Full path where to the endpoint that will be written
	Path pulumi.StringPtrInput
	// Map of strings returned by write operation
	WriteData pulumi.StringMapInput
	// JSON data returned by write operation
	WriteDataJson pulumi.StringPtrInput
	// Top-level fields returned by write to persist in state
	WriteFields pulumi.StringArrayInput
}

func (EndpointState) ElementType() reflect.Type {
	return reflect.TypeOf((*endpointState)(nil)).Elem()
}

type endpointArgs struct {
	// JSON-encoded data to write.
	DataJson string `pulumi:"dataJson"`
	// Don't attempt to delete the path from Vault if true
	DisableDelete *bool `pulumi:"disableDelete"`
	// Don't attempt to read the path from Vault if true; drift won't be detected
	DisableRead *bool `pulumi:"disableRead"`
	// When reading, disregard fields not present in data_json
	IgnoreAbsentFields *bool `pulumi:"ignoreAbsentFields"`
	// Full path where to the endpoint that will be written
	Path string `pulumi:"path"`
	// Top-level fields returned by write to persist in state
	WriteFields []string `pulumi:"writeFields"`
}

// The set of arguments for constructing a Endpoint resource.
type EndpointArgs struct {
	// JSON-encoded data to write.
	DataJson pulumi.StringInput
	// Don't attempt to delete the path from Vault if true
	DisableDelete pulumi.BoolPtrInput
	// Don't attempt to read the path from Vault if true; drift won't be detected
	DisableRead pulumi.BoolPtrInput
	// When reading, disregard fields not present in data_json
	IgnoreAbsentFields pulumi.BoolPtrInput
	// Full path where to the endpoint that will be written
	Path pulumi.StringInput
	// Top-level fields returned by write to persist in state
	WriteFields pulumi.StringArrayInput
}

func (EndpointArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*endpointArgs)(nil)).Elem()
}

