// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class AuthBackendRoleTag extends pulumi.CustomResource {
    /**
     * Get an existing AuthBackendRoleTag resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AuthBackendRoleTagState, opts?: pulumi.CustomResourceOptions): AuthBackendRoleTag {
        return new AuthBackendRoleTag(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vault:aws/authBackendRoleTag:AuthBackendRoleTag';

    /**
     * Returns true if the given object is an instance of AuthBackendRoleTag.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AuthBackendRoleTag {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AuthBackendRoleTag.__pulumiType;
    }

    /**
     * Allows migration of the underlying instance where the client resides.
     */
    public readonly allowInstanceMigration!: pulumi.Output<boolean | undefined>;
    /**
     * AWS auth backend to read tags from.
     */
    public readonly backend!: pulumi.Output<string | undefined>;
    /**
     * Only allow a single token to be granted per instance ID.
     */
    public readonly disallowReauthentication!: pulumi.Output<boolean | undefined>;
    /**
     * Instance ID for which this tag is intended. The created tag can only be used by the instance with the given ID.
     */
    public readonly instanceId!: pulumi.Output<string | undefined>;
    /**
     * The maximum allowed lifetime of tokens issued using this role.
     */
    public readonly maxTtl!: pulumi.Output<string | undefined>;
    /**
     * Policies to be associated with the tag.
     */
    public readonly policies!: pulumi.Output<string[] | undefined>;
    /**
     * Name of the role.
     */
    public readonly role!: pulumi.Output<string>;
    public /*out*/ readonly tagKey!: pulumi.Output<string>;
    public /*out*/ readonly tagValue!: pulumi.Output<string>;

    /**
     * Create a AuthBackendRoleTag resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AuthBackendRoleTagArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AuthBackendRoleTagArgs | AuthBackendRoleTagState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as AuthBackendRoleTagState | undefined;
            inputs["allowInstanceMigration"] = state ? state.allowInstanceMigration : undefined;
            inputs["backend"] = state ? state.backend : undefined;
            inputs["disallowReauthentication"] = state ? state.disallowReauthentication : undefined;
            inputs["instanceId"] = state ? state.instanceId : undefined;
            inputs["maxTtl"] = state ? state.maxTtl : undefined;
            inputs["policies"] = state ? state.policies : undefined;
            inputs["role"] = state ? state.role : undefined;
            inputs["tagKey"] = state ? state.tagKey : undefined;
            inputs["tagValue"] = state ? state.tagValue : undefined;
        } else {
            const args = argsOrState as AuthBackendRoleTagArgs | undefined;
            if (!args || args.role === undefined) {
                throw new Error("Missing required property 'role'");
            }
            inputs["allowInstanceMigration"] = args ? args.allowInstanceMigration : undefined;
            inputs["backend"] = args ? args.backend : undefined;
            inputs["disallowReauthentication"] = args ? args.disallowReauthentication : undefined;
            inputs["instanceId"] = args ? args.instanceId : undefined;
            inputs["maxTtl"] = args ? args.maxTtl : undefined;
            inputs["policies"] = args ? args.policies : undefined;
            inputs["role"] = args ? args.role : undefined;
            inputs["tagKey"] = undefined /*out*/;
            inputs["tagValue"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(AuthBackendRoleTag.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AuthBackendRoleTag resources.
 */
export interface AuthBackendRoleTagState {
    /**
     * Allows migration of the underlying instance where the client resides.
     */
    readonly allowInstanceMigration?: pulumi.Input<boolean>;
    /**
     * AWS auth backend to read tags from.
     */
    readonly backend?: pulumi.Input<string>;
    /**
     * Only allow a single token to be granted per instance ID.
     */
    readonly disallowReauthentication?: pulumi.Input<boolean>;
    /**
     * Instance ID for which this tag is intended. The created tag can only be used by the instance with the given ID.
     */
    readonly instanceId?: pulumi.Input<string>;
    /**
     * The maximum allowed lifetime of tokens issued using this role.
     */
    readonly maxTtl?: pulumi.Input<string>;
    /**
     * Policies to be associated with the tag.
     */
    readonly policies?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Name of the role.
     */
    readonly role?: pulumi.Input<string>;
    readonly tagKey?: pulumi.Input<string>;
    readonly tagValue?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AuthBackendRoleTag resource.
 */
export interface AuthBackendRoleTagArgs {
    /**
     * Allows migration of the underlying instance where the client resides.
     */
    readonly allowInstanceMigration?: pulumi.Input<boolean>;
    /**
     * AWS auth backend to read tags from.
     */
    readonly backend?: pulumi.Input<string>;
    /**
     * Only allow a single token to be granted per instance ID.
     */
    readonly disallowReauthentication?: pulumi.Input<boolean>;
    /**
     * Instance ID for which this tag is intended. The created tag can only be used by the instance with the given ID.
     */
    readonly instanceId?: pulumi.Input<string>;
    /**
     * The maximum allowed lifetime of tokens issued using this role.
     */
    readonly maxTtl?: pulumi.Input<string>;
    /**
     * Policies to be associated with the tag.
     */
    readonly policies?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Name of the role.
     */
    readonly role: pulumi.Input<string>;
}
