// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class AuthBackendCert extends pulumi.CustomResource {
    /**
     * Get an existing AuthBackendCert resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AuthBackendCertState, opts?: pulumi.CustomResourceOptions): AuthBackendCert {
        return new AuthBackendCert(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vault:aws/authBackendCert:AuthBackendCert';

    /**
     * Returns true if the given object is an instance of AuthBackendCert.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AuthBackendCert {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AuthBackendCert.__pulumiType;
    }

    /**
     * Base64 encoded AWS Public key required to verify PKCS7 signature of the EC2 instance metadata.
     */
    public readonly awsPublicCert!: pulumi.Output<string>;
    /**
     * Unique name of the auth backend to configure.
     */
    public readonly backend!: pulumi.Output<string | undefined>;
    /**
     * Name of the certificate to configure.
     */
    public readonly certName!: pulumi.Output<string>;
    /**
     * The type of document that can be verified using the certificate. Must be either "pkcs7" or "identity".
     */
    public readonly type!: pulumi.Output<string | undefined>;

    /**
     * Create a AuthBackendCert resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AuthBackendCertArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AuthBackendCertArgs | AuthBackendCertState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as AuthBackendCertState | undefined;
            inputs["awsPublicCert"] = state ? state.awsPublicCert : undefined;
            inputs["backend"] = state ? state.backend : undefined;
            inputs["certName"] = state ? state.certName : undefined;
            inputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as AuthBackendCertArgs | undefined;
            if (!args || args.awsPublicCert === undefined) {
                throw new Error("Missing required property 'awsPublicCert'");
            }
            if (!args || args.certName === undefined) {
                throw new Error("Missing required property 'certName'");
            }
            inputs["awsPublicCert"] = args ? args.awsPublicCert : undefined;
            inputs["backend"] = args ? args.backend : undefined;
            inputs["certName"] = args ? args.certName : undefined;
            inputs["type"] = args ? args.type : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(AuthBackendCert.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AuthBackendCert resources.
 */
export interface AuthBackendCertState {
    /**
     * Base64 encoded AWS Public key required to verify PKCS7 signature of the EC2 instance metadata.
     */
    readonly awsPublicCert?: pulumi.Input<string>;
    /**
     * Unique name of the auth backend to configure.
     */
    readonly backend?: pulumi.Input<string>;
    /**
     * Name of the certificate to configure.
     */
    readonly certName?: pulumi.Input<string>;
    /**
     * The type of document that can be verified using the certificate. Must be either "pkcs7" or "identity".
     */
    readonly type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AuthBackendCert resource.
 */
export interface AuthBackendCertArgs {
    /**
     * Base64 encoded AWS Public key required to verify PKCS7 signature of the EC2 instance metadata.
     */
    readonly awsPublicCert: pulumi.Input<string>;
    /**
     * Unique name of the auth backend to configure.
     */
    readonly backend?: pulumi.Input<string>;
    /**
     * Name of the certificate to configure.
     */
    readonly certName: pulumi.Input<string>;
    /**
     * The type of document that can be verified using the certificate. Must be either "pkcs7" or "identity".
     */
    readonly type?: pulumi.Input<string>;
}
