// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class SecretBackendRole extends pulumi.CustomResource {
    /**
     * Get an existing SecretBackendRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretBackendRoleState, opts?: pulumi.CustomResourceOptions): SecretBackendRole {
        return new SecretBackendRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vault:aws/secretBackendRole:SecretBackendRole';

    /**
     * Returns true if the given object is an instance of SecretBackendRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretBackendRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretBackendRole.__pulumiType;
    }

    /**
     * The path of the AWS Secret Backend the role belongs to.
     */
    public readonly backend!: pulumi.Output<string>;
    /**
     * Role credential type.
     */
    public readonly credentialType!: pulumi.Output<string>;
    /**
     * The default TTL in seconds for STS credentials. When a TTL is not specified when STS credentials are requested, and
     * a default TTL is specified on the role, then this default TTL will be used. Valid only when credential_type is one
     * of assumed_role or federation_token.
     */
    public readonly defaultStsTtl!: pulumi.Output<number>;
    /**
     * The max allowed TTL in seconds for STS credentials (credentials TTL are capped to max_sts_ttl). Valid only when
     * credential_type is one of assumed_role or federation_token.
     */
    public readonly maxStsTtl!: pulumi.Output<number>;
    /**
     * Unique name for the role.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * ARN for an existing IAM policy the role should use.
     */
    public readonly policyArns!: pulumi.Output<string[] | undefined>;
    /**
     * IAM policy the role should use in JSON format.
     */
    public readonly policyDocument!: pulumi.Output<string | undefined>;
    /**
     * ARNs of AWS roles allowed to be assumed. Only valid when credential_type is 'assumed_role'
     */
    public readonly roleArns!: pulumi.Output<string[] | undefined>;

    /**
     * Create a SecretBackendRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretBackendRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretBackendRoleArgs | SecretBackendRoleState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as SecretBackendRoleState | undefined;
            inputs["backend"] = state ? state.backend : undefined;
            inputs["credentialType"] = state ? state.credentialType : undefined;
            inputs["defaultStsTtl"] = state ? state.defaultStsTtl : undefined;
            inputs["maxStsTtl"] = state ? state.maxStsTtl : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["policyArns"] = state ? state.policyArns : undefined;
            inputs["policyDocument"] = state ? state.policyDocument : undefined;
            inputs["roleArns"] = state ? state.roleArns : undefined;
        } else {
            const args = argsOrState as SecretBackendRoleArgs | undefined;
            if (!args || args.backend === undefined) {
                throw new Error("Missing required property 'backend'");
            }
            if (!args || args.credentialType === undefined) {
                throw new Error("Missing required property 'credentialType'");
            }
            inputs["backend"] = args ? args.backend : undefined;
            inputs["credentialType"] = args ? args.credentialType : undefined;
            inputs["defaultStsTtl"] = args ? args.defaultStsTtl : undefined;
            inputs["maxStsTtl"] = args ? args.maxStsTtl : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["policyArns"] = args ? args.policyArns : undefined;
            inputs["policyDocument"] = args ? args.policyDocument : undefined;
            inputs["roleArns"] = args ? args.roleArns : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(SecretBackendRole.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretBackendRole resources.
 */
export interface SecretBackendRoleState {
    /**
     * The path of the AWS Secret Backend the role belongs to.
     */
    readonly backend?: pulumi.Input<string>;
    /**
     * Role credential type.
     */
    readonly credentialType?: pulumi.Input<string>;
    /**
     * The default TTL in seconds for STS credentials. When a TTL is not specified when STS credentials are requested, and
     * a default TTL is specified on the role, then this default TTL will be used. Valid only when credential_type is one
     * of assumed_role or federation_token.
     */
    readonly defaultStsTtl?: pulumi.Input<number>;
    /**
     * The max allowed TTL in seconds for STS credentials (credentials TTL are capped to max_sts_ttl). Valid only when
     * credential_type is one of assumed_role or federation_token.
     */
    readonly maxStsTtl?: pulumi.Input<number>;
    /**
     * Unique name for the role.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * ARN for an existing IAM policy the role should use.
     */
    readonly policyArns?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * IAM policy the role should use in JSON format.
     */
    readonly policyDocument?: pulumi.Input<string>;
    /**
     * ARNs of AWS roles allowed to be assumed. Only valid when credential_type is 'assumed_role'
     */
    readonly roleArns?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a SecretBackendRole resource.
 */
export interface SecretBackendRoleArgs {
    /**
     * The path of the AWS Secret Backend the role belongs to.
     */
    readonly backend: pulumi.Input<string>;
    /**
     * Role credential type.
     */
    readonly credentialType: pulumi.Input<string>;
    /**
     * The default TTL in seconds for STS credentials. When a TTL is not specified when STS credentials are requested, and
     * a default TTL is specified on the role, then this default TTL will be used. Valid only when credential_type is one
     * of assumed_role or federation_token.
     */
    readonly defaultStsTtl?: pulumi.Input<number>;
    /**
     * The max allowed TTL in seconds for STS credentials (credentials TTL are capped to max_sts_ttl). Valid only when
     * credential_type is one of assumed_role or federation_token.
     */
    readonly maxStsTtl?: pulumi.Input<number>;
    /**
     * Unique name for the role.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * ARN for an existing IAM policy the role should use.
     */
    readonly policyArns?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * IAM policy the role should use in JSON format.
     */
    readonly policyDocument?: pulumi.Input<string>;
    /**
     * ARNs of AWS roles allowed to be assumed. Only valid when credential_type is 'assumed_role'
     */
    readonly roleArns?: pulumi.Input<pulumi.Input<string>[]>;
}
