// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class AuthBackend extends pulumi.CustomResource {
    /**
     * Get an existing AuthBackend resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AuthBackendState, opts?: pulumi.CustomResourceOptions): AuthBackend {
        return new AuthBackend(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vault:gcp/authBackend:AuthBackend';

    /**
     * Returns true if the given object is an instance of AuthBackend.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AuthBackend {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AuthBackend.__pulumiType;
    }

    public readonly clientEmail!: pulumi.Output<string>;
    public readonly clientId!: pulumi.Output<string>;
    public readonly credentials!: pulumi.Output<string | undefined>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly path!: pulumi.Output<string | undefined>;
    public readonly privateKeyId!: pulumi.Output<string>;
    public readonly projectId!: pulumi.Output<string>;

    /**
     * Create a AuthBackend resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AuthBackendArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AuthBackendArgs | AuthBackendState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as AuthBackendState | undefined;
            inputs["clientEmail"] = state ? state.clientEmail : undefined;
            inputs["clientId"] = state ? state.clientId : undefined;
            inputs["credentials"] = state ? state.credentials : undefined;
            inputs["description"] = state ? state.description : undefined;
            inputs["path"] = state ? state.path : undefined;
            inputs["privateKeyId"] = state ? state.privateKeyId : undefined;
            inputs["projectId"] = state ? state.projectId : undefined;
        } else {
            const args = argsOrState as AuthBackendArgs | undefined;
            inputs["clientEmail"] = args ? args.clientEmail : undefined;
            inputs["clientId"] = args ? args.clientId : undefined;
            inputs["credentials"] = args ? args.credentials : undefined;
            inputs["description"] = args ? args.description : undefined;
            inputs["path"] = args ? args.path : undefined;
            inputs["privateKeyId"] = args ? args.privateKeyId : undefined;
            inputs["projectId"] = args ? args.projectId : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(AuthBackend.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AuthBackend resources.
 */
export interface AuthBackendState {
    readonly clientEmail?: pulumi.Input<string>;
    readonly clientId?: pulumi.Input<string>;
    readonly credentials?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly path?: pulumi.Input<string>;
    readonly privateKeyId?: pulumi.Input<string>;
    readonly projectId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AuthBackend resource.
 */
export interface AuthBackendArgs {
    readonly clientEmail?: pulumi.Input<string>;
    readonly clientId?: pulumi.Input<string>;
    readonly credentials?: pulumi.Input<string>;
    readonly description?: pulumi.Input<string>;
    readonly path?: pulumi.Input<string>;
    readonly privateKeyId?: pulumi.Input<string>;
    readonly projectId?: pulumi.Input<string>;
}
