// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package aws

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type AuthBackendLogin struct {
	pulumi.CustomResourceState

	// The accessor returned from Vault for this token.
	Accessor pulumi.StringOutput `pulumi:"accessor"`
	// The auth method used to generate this token.
	AuthType pulumi.StringOutput `pulumi:"authType"`
	// AWS Auth Backend to read the token from.
	Backend pulumi.StringPtrOutput `pulumi:"backend"`
	// The token returned by Vault.
	ClientToken pulumi.StringOutput `pulumi:"clientToken"`
	// The HTTP method used in the signed request.
	IamHttpRequestMethod pulumi.StringPtrOutput `pulumi:"iamHttpRequestMethod"`
	// The Base64-encoded body of the signed request.
	IamRequestBody pulumi.StringPtrOutput `pulumi:"iamRequestBody"`
	// The Base64-encoded, JSON serialized representation of the sts:GetCallerIdentity HTTP request headers.
	IamRequestHeaders pulumi.StringPtrOutput `pulumi:"iamRequestHeaders"`
	// The Base64-encoded HTTP URL used in the signed request.
	IamRequestUrl pulumi.StringPtrOutput `pulumi:"iamRequestUrl"`
	// Base64-encoded EC2 instance identity document to authenticate with.
	Identity pulumi.StringPtrOutput `pulumi:"identity"`
	// Lease duration in seconds relative to the time in lease_start_time.
	LeaseDuration pulumi.IntOutput `pulumi:"leaseDuration"`
	// Time at which the lease was read, using the clock of the system where Terraform was running
	LeaseStartTime pulumi.StringOutput `pulumi:"leaseStartTime"`
	// The metadata reported by the Vault server.
	Metadata pulumi.MapOutput `pulumi:"metadata"`
	// The nonce to be used for subsequent login requests.
	Nonce pulumi.StringOutput `pulumi:"nonce"`
	// PKCS7 signature of the identity document to authenticate with, with all newline characters removed.
	Pkcs7 pulumi.StringPtrOutput `pulumi:"pkcs7"`
	// The policies assigned to this token.
	Policies pulumi.StringArrayOutput `pulumi:"policies"`
	// True if the duration of this lease can be extended through renewal.
	Renewable pulumi.BoolOutput `pulumi:"renewable"`
	// AWS Auth Role to read the token from.
	Role pulumi.StringOutput `pulumi:"role"`
	// Base64-encoded SHA256 RSA signature of the instance identtiy document to authenticate with.
	Signature pulumi.StringPtrOutput `pulumi:"signature"`
}

// NewAuthBackendLogin registers a new resource with the given unique name, arguments, and options.
func NewAuthBackendLogin(ctx *pulumi.Context,
	name string, args *AuthBackendLoginArgs, opts ...pulumi.ResourceOption) (*AuthBackendLogin, error) {
	if args == nil {
		args = &AuthBackendLoginArgs{}
	}
	var resource AuthBackendLogin
	err := ctx.RegisterResource("vault:aws/authBackendLogin:AuthBackendLogin", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuthBackendLogin gets an existing AuthBackendLogin resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuthBackendLogin(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuthBackendLoginState, opts ...pulumi.ResourceOption) (*AuthBackendLogin, error) {
	var resource AuthBackendLogin
	err := ctx.ReadResource("vault:aws/authBackendLogin:AuthBackendLogin", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AuthBackendLogin resources.
type authBackendLoginState struct {
	// The accessor returned from Vault for this token.
	Accessor *string `pulumi:"accessor"`
	// The auth method used to generate this token.
	AuthType *string `pulumi:"authType"`
	// AWS Auth Backend to read the token from.
	Backend *string `pulumi:"backend"`
	// The token returned by Vault.
	ClientToken *string `pulumi:"clientToken"`
	// The HTTP method used in the signed request.
	IamHttpRequestMethod *string `pulumi:"iamHttpRequestMethod"`
	// The Base64-encoded body of the signed request.
	IamRequestBody *string `pulumi:"iamRequestBody"`
	// The Base64-encoded, JSON serialized representation of the sts:GetCallerIdentity HTTP request headers.
	IamRequestHeaders *string `pulumi:"iamRequestHeaders"`
	// The Base64-encoded HTTP URL used in the signed request.
	IamRequestUrl *string `pulumi:"iamRequestUrl"`
	// Base64-encoded EC2 instance identity document to authenticate with.
	Identity *string `pulumi:"identity"`
	// Lease duration in seconds relative to the time in lease_start_time.
	LeaseDuration *int `pulumi:"leaseDuration"`
	// Time at which the lease was read, using the clock of the system where Terraform was running
	LeaseStartTime *string `pulumi:"leaseStartTime"`
	// The metadata reported by the Vault server.
	Metadata map[string]interface{} `pulumi:"metadata"`
	// The nonce to be used for subsequent login requests.
	Nonce *string `pulumi:"nonce"`
	// PKCS7 signature of the identity document to authenticate with, with all newline characters removed.
	Pkcs7 *string `pulumi:"pkcs7"`
	// The policies assigned to this token.
	Policies []string `pulumi:"policies"`
	// True if the duration of this lease can be extended through renewal.
	Renewable *bool `pulumi:"renewable"`
	// AWS Auth Role to read the token from.
	Role *string `pulumi:"role"`
	// Base64-encoded SHA256 RSA signature of the instance identtiy document to authenticate with.
	Signature *string `pulumi:"signature"`
}

type AuthBackendLoginState struct {
	// The accessor returned from Vault for this token.
	Accessor pulumi.StringPtrInput
	// The auth method used to generate this token.
	AuthType pulumi.StringPtrInput
	// AWS Auth Backend to read the token from.
	Backend pulumi.StringPtrInput
	// The token returned by Vault.
	ClientToken pulumi.StringPtrInput
	// The HTTP method used in the signed request.
	IamHttpRequestMethod pulumi.StringPtrInput
	// The Base64-encoded body of the signed request.
	IamRequestBody pulumi.StringPtrInput
	// The Base64-encoded, JSON serialized representation of the sts:GetCallerIdentity HTTP request headers.
	IamRequestHeaders pulumi.StringPtrInput
	// The Base64-encoded HTTP URL used in the signed request.
	IamRequestUrl pulumi.StringPtrInput
	// Base64-encoded EC2 instance identity document to authenticate with.
	Identity pulumi.StringPtrInput
	// Lease duration in seconds relative to the time in lease_start_time.
	LeaseDuration pulumi.IntPtrInput
	// Time at which the lease was read, using the clock of the system where Terraform was running
	LeaseStartTime pulumi.StringPtrInput
	// The metadata reported by the Vault server.
	Metadata pulumi.MapInput
	// The nonce to be used for subsequent login requests.
	Nonce pulumi.StringPtrInput
	// PKCS7 signature of the identity document to authenticate with, with all newline characters removed.
	Pkcs7 pulumi.StringPtrInput
	// The policies assigned to this token.
	Policies pulumi.StringArrayInput
	// True if the duration of this lease can be extended through renewal.
	Renewable pulumi.BoolPtrInput
	// AWS Auth Role to read the token from.
	Role pulumi.StringPtrInput
	// Base64-encoded SHA256 RSA signature of the instance identtiy document to authenticate with.
	Signature pulumi.StringPtrInput
}

func (AuthBackendLoginState) ElementType() reflect.Type {
	return reflect.TypeOf((*authBackendLoginState)(nil)).Elem()
}

type authBackendLoginArgs struct {
	// AWS Auth Backend to read the token from.
	Backend *string `pulumi:"backend"`
	// The HTTP method used in the signed request.
	IamHttpRequestMethod *string `pulumi:"iamHttpRequestMethod"`
	// The Base64-encoded body of the signed request.
	IamRequestBody *string `pulumi:"iamRequestBody"`
	// The Base64-encoded, JSON serialized representation of the sts:GetCallerIdentity HTTP request headers.
	IamRequestHeaders *string `pulumi:"iamRequestHeaders"`
	// The Base64-encoded HTTP URL used in the signed request.
	IamRequestUrl *string `pulumi:"iamRequestUrl"`
	// Base64-encoded EC2 instance identity document to authenticate with.
	Identity *string `pulumi:"identity"`
	// The nonce to be used for subsequent login requests.
	Nonce *string `pulumi:"nonce"`
	// PKCS7 signature of the identity document to authenticate with, with all newline characters removed.
	Pkcs7 *string `pulumi:"pkcs7"`
	// AWS Auth Role to read the token from.
	Role *string `pulumi:"role"`
	// Base64-encoded SHA256 RSA signature of the instance identtiy document to authenticate with.
	Signature *string `pulumi:"signature"`
}

// The set of arguments for constructing a AuthBackendLogin resource.
type AuthBackendLoginArgs struct {
	// AWS Auth Backend to read the token from.
	Backend pulumi.StringPtrInput
	// The HTTP method used in the signed request.
	IamHttpRequestMethod pulumi.StringPtrInput
	// The Base64-encoded body of the signed request.
	IamRequestBody pulumi.StringPtrInput
	// The Base64-encoded, JSON serialized representation of the sts:GetCallerIdentity HTTP request headers.
	IamRequestHeaders pulumi.StringPtrInput
	// The Base64-encoded HTTP URL used in the signed request.
	IamRequestUrl pulumi.StringPtrInput
	// Base64-encoded EC2 instance identity document to authenticate with.
	Identity pulumi.StringPtrInput
	// The nonce to be used for subsequent login requests.
	Nonce pulumi.StringPtrInput
	// PKCS7 signature of the identity document to authenticate with, with all newline characters removed.
	Pkcs7 pulumi.StringPtrInput
	// AWS Auth Role to read the token from.
	Role pulumi.StringPtrInput
	// Base64-encoded SHA256 RSA signature of the instance identtiy document to authenticate with.
	Signature pulumi.StringPtrInput
}

func (AuthBackendLoginArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*authBackendLoginArgs)(nil)).Elem()
}

