// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package aws

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type AuthBackendStsRole struct {
	pulumi.CustomResourceState

	// AWS account ID to be associated with STS role.
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// Unique name of the auth backend to configure.
	Backend pulumi.StringPtrOutput `pulumi:"backend"`
	// AWS ARN for STS role to be assumed when interacting with the account specified.
	StsRole pulumi.StringOutput `pulumi:"stsRole"`
}

// NewAuthBackendStsRole registers a new resource with the given unique name, arguments, and options.
func NewAuthBackendStsRole(ctx *pulumi.Context,
	name string, args *AuthBackendStsRoleArgs, opts ...pulumi.ResourceOption) (*AuthBackendStsRole, error) {
	if args == nil || args.AccountId == nil {
		return nil, errors.New("missing required argument 'AccountId'")
	}
	if args == nil || args.StsRole == nil {
		return nil, errors.New("missing required argument 'StsRole'")
	}
	if args == nil {
		args = &AuthBackendStsRoleArgs{}
	}
	var resource AuthBackendStsRole
	err := ctx.RegisterResource("vault:aws/authBackendStsRole:AuthBackendStsRole", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAuthBackendStsRole gets an existing AuthBackendStsRole resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAuthBackendStsRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AuthBackendStsRoleState, opts ...pulumi.ResourceOption) (*AuthBackendStsRole, error) {
	var resource AuthBackendStsRole
	err := ctx.ReadResource("vault:aws/authBackendStsRole:AuthBackendStsRole", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AuthBackendStsRole resources.
type authBackendStsRoleState struct {
	// AWS account ID to be associated with STS role.
	AccountId *string `pulumi:"accountId"`
	// Unique name of the auth backend to configure.
	Backend *string `pulumi:"backend"`
	// AWS ARN for STS role to be assumed when interacting with the account specified.
	StsRole *string `pulumi:"stsRole"`
}

type AuthBackendStsRoleState struct {
	// AWS account ID to be associated with STS role.
	AccountId pulumi.StringPtrInput
	// Unique name of the auth backend to configure.
	Backend pulumi.StringPtrInput
	// AWS ARN for STS role to be assumed when interacting with the account specified.
	StsRole pulumi.StringPtrInput
}

func (AuthBackendStsRoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*authBackendStsRoleState)(nil)).Elem()
}

type authBackendStsRoleArgs struct {
	// AWS account ID to be associated with STS role.
	AccountId string `pulumi:"accountId"`
	// Unique name of the auth backend to configure.
	Backend *string `pulumi:"backend"`
	// AWS ARN for STS role to be assumed when interacting with the account specified.
	StsRole string `pulumi:"stsRole"`
}

// The set of arguments for constructing a AuthBackendStsRole resource.
type AuthBackendStsRoleArgs struct {
	// AWS account ID to be associated with STS role.
	AccountId pulumi.StringInput
	// Unique name of the auth backend to configure.
	Backend pulumi.StringPtrInput
	// AWS ARN for STS role to be assumed when interacting with the account specified.
	StsRole pulumi.StringInput
}

func (AuthBackendStsRoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*authBackendStsRoleArgs)(nil)).Elem()
}

