// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package aws

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func GetAccessCredentials(ctx *pulumi.Context, args *GetAccessCredentialsArgs, opts ...pulumi.InvokeOption) (*GetAccessCredentialsResult, error) {
	var rv GetAccessCredentialsResult
	err := ctx.Invoke("vault:aws/getAccessCredentials:getAccessCredentials", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccessCredentials.
type GetAccessCredentialsArgs struct {
	Backend string `pulumi:"backend"`
	Role string `pulumi:"role"`
	RoleArn *string `pulumi:"roleArn"`
	Type *string `pulumi:"type"`
}


// A collection of values returned by getAccessCredentials.
type GetAccessCredentialsResult struct {
	AccessKey string `pulumi:"accessKey"`
	Backend string `pulumi:"backend"`
	// id is the provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	LeaseDuration int `pulumi:"leaseDuration"`
	LeaseId string `pulumi:"leaseId"`
	LeaseRenewable bool `pulumi:"leaseRenewable"`
	LeaseStartTime string `pulumi:"leaseStartTime"`
	Role string `pulumi:"role"`
	RoleArn *string `pulumi:"roleArn"`
	SecretKey string `pulumi:"secretKey"`
	SecurityToken string `pulumi:"securityToken"`
	Type *string `pulumi:"type"`
}

