// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package rabbitMq

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type SecretBackendRoleVhost struct {
	Configure string `pulumi:"configure"`
	Host      string `pulumi:"host"`
	Read      string `pulumi:"read"`
	Write     string `pulumi:"write"`
}

type SecretBackendRoleVhostInput interface {
	pulumi.Input

	ToSecretBackendRoleVhostOutput() SecretBackendRoleVhostOutput
	ToSecretBackendRoleVhostOutputWithContext(context.Context) SecretBackendRoleVhostOutput
}

type SecretBackendRoleVhostArgs struct {
	Configure pulumi.StringInput `pulumi:"configure"`
	Host      pulumi.StringInput `pulumi:"host"`
	Read      pulumi.StringInput `pulumi:"read"`
	Write     pulumi.StringInput `pulumi:"write"`
}

func (SecretBackendRoleVhostArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretBackendRoleVhost)(nil)).Elem()
}

func (i SecretBackendRoleVhostArgs) ToSecretBackendRoleVhostOutput() SecretBackendRoleVhostOutput {
	return i.ToSecretBackendRoleVhostOutputWithContext(context.Background())
}

func (i SecretBackendRoleVhostArgs) ToSecretBackendRoleVhostOutputWithContext(ctx context.Context) SecretBackendRoleVhostOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretBackendRoleVhostOutput)
}

type SecretBackendRoleVhostArrayInput interface {
	pulumi.Input

	ToSecretBackendRoleVhostArrayOutput() SecretBackendRoleVhostArrayOutput
	ToSecretBackendRoleVhostArrayOutputWithContext(context.Context) SecretBackendRoleVhostArrayOutput
}

type SecretBackendRoleVhostArray []SecretBackendRoleVhostInput

func (SecretBackendRoleVhostArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SecretBackendRoleVhost)(nil)).Elem()
}

func (i SecretBackendRoleVhostArray) ToSecretBackendRoleVhostArrayOutput() SecretBackendRoleVhostArrayOutput {
	return i.ToSecretBackendRoleVhostArrayOutputWithContext(context.Background())
}

func (i SecretBackendRoleVhostArray) ToSecretBackendRoleVhostArrayOutputWithContext(ctx context.Context) SecretBackendRoleVhostArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretBackendRoleVhostArrayOutput)
}

type SecretBackendRoleVhostOutput struct{ *pulumi.OutputState }

func (SecretBackendRoleVhostOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretBackendRoleVhost)(nil)).Elem()
}

func (o SecretBackendRoleVhostOutput) ToSecretBackendRoleVhostOutput() SecretBackendRoleVhostOutput {
	return o
}

func (o SecretBackendRoleVhostOutput) ToSecretBackendRoleVhostOutputWithContext(ctx context.Context) SecretBackendRoleVhostOutput {
	return o
}

func (o SecretBackendRoleVhostOutput) Configure() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhost) string { return v.Configure }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhost) string { return v.Host }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostOutput) Read() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhost) string { return v.Read }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostOutput) Write() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhost) string { return v.Write }).(pulumi.StringOutput)
}

type SecretBackendRoleVhostArrayOutput struct{ *pulumi.OutputState }

func (SecretBackendRoleVhostArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SecretBackendRoleVhost)(nil)).Elem()
}

func (o SecretBackendRoleVhostArrayOutput) ToSecretBackendRoleVhostArrayOutput() SecretBackendRoleVhostArrayOutput {
	return o
}

func (o SecretBackendRoleVhostArrayOutput) ToSecretBackendRoleVhostArrayOutputWithContext(ctx context.Context) SecretBackendRoleVhostArrayOutput {
	return o
}

func (o SecretBackendRoleVhostArrayOutput) Index(i pulumi.IntInput) SecretBackendRoleVhostOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) SecretBackendRoleVhost {
		return vs[0].([]SecretBackendRoleVhost)[vs[1].(int)]
	}).(SecretBackendRoleVhostOutput)
}

type SecretBackendRoleVhostArgs struct {
	Configure string `pulumi:"configure"`
	Host      string `pulumi:"host"`
	Read      string `pulumi:"read"`
	Write     string `pulumi:"write"`
}

type SecretBackendRoleVhostArgsInput interface {
	pulumi.Input

	ToSecretBackendRoleVhostArgsOutput() SecretBackendRoleVhostArgsOutput
	ToSecretBackendRoleVhostArgsOutputWithContext(context.Context) SecretBackendRoleVhostArgsOutput
}

type SecretBackendRoleVhostArgsArgs struct {
	Configure pulumi.StringInput `pulumi:"configure"`
	Host      pulumi.StringInput `pulumi:"host"`
	Read      pulumi.StringInput `pulumi:"read"`
	Write     pulumi.StringInput `pulumi:"write"`
}

func (SecretBackendRoleVhostArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretBackendRoleVhostArgs)(nil)).Elem()
}

func (i SecretBackendRoleVhostArgsArgs) ToSecretBackendRoleVhostArgsOutput() SecretBackendRoleVhostArgsOutput {
	return i.ToSecretBackendRoleVhostArgsOutputWithContext(context.Background())
}

func (i SecretBackendRoleVhostArgsArgs) ToSecretBackendRoleVhostArgsOutputWithContext(ctx context.Context) SecretBackendRoleVhostArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretBackendRoleVhostArgsOutput)
}

type SecretBackendRoleVhostArgsArrayInput interface {
	pulumi.Input

	ToSecretBackendRoleVhostArgsArrayOutput() SecretBackendRoleVhostArgsArrayOutput
	ToSecretBackendRoleVhostArgsArrayOutputWithContext(context.Context) SecretBackendRoleVhostArgsArrayOutput
}

type SecretBackendRoleVhostArgsArray []SecretBackendRoleVhostArgsInput

func (SecretBackendRoleVhostArgsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SecretBackendRoleVhostArgs)(nil)).Elem()
}

func (i SecretBackendRoleVhostArgsArray) ToSecretBackendRoleVhostArgsArrayOutput() SecretBackendRoleVhostArgsArrayOutput {
	return i.ToSecretBackendRoleVhostArgsArrayOutputWithContext(context.Background())
}

func (i SecretBackendRoleVhostArgsArray) ToSecretBackendRoleVhostArgsArrayOutputWithContext(ctx context.Context) SecretBackendRoleVhostArgsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretBackendRoleVhostArgsArrayOutput)
}

type SecretBackendRoleVhostArgsOutput struct{ *pulumi.OutputState }

func (SecretBackendRoleVhostArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretBackendRoleVhostArgs)(nil)).Elem()
}

func (o SecretBackendRoleVhostArgsOutput) ToSecretBackendRoleVhostArgsOutput() SecretBackendRoleVhostArgsOutput {
	return o
}

func (o SecretBackendRoleVhostArgsOutput) ToSecretBackendRoleVhostArgsOutputWithContext(ctx context.Context) SecretBackendRoleVhostArgsOutput {
	return o
}

func (o SecretBackendRoleVhostArgsOutput) Configure() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhostArgs) string { return v.Configure }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostArgsOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhostArgs) string { return v.Host }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostArgsOutput) Read() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhostArgs) string { return v.Read }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostArgsOutput) Write() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhostArgs) string { return v.Write }).(pulumi.StringOutput)
}

type SecretBackendRoleVhostArgsArrayOutput struct{ *pulumi.OutputState }

func (SecretBackendRoleVhostArgsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SecretBackendRoleVhostArgs)(nil)).Elem()
}

func (o SecretBackendRoleVhostArgsArrayOutput) ToSecretBackendRoleVhostArgsArrayOutput() SecretBackendRoleVhostArgsArrayOutput {
	return o
}

func (o SecretBackendRoleVhostArgsArrayOutput) ToSecretBackendRoleVhostArgsArrayOutputWithContext(ctx context.Context) SecretBackendRoleVhostArgsArrayOutput {
	return o
}

func (o SecretBackendRoleVhostArgsArrayOutput) Index(i pulumi.IntInput) SecretBackendRoleVhostArgsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) SecretBackendRoleVhostArgs {
		return vs[0].([]SecretBackendRoleVhostArgs)[vs[1].(int)]
	}).(SecretBackendRoleVhostArgsOutput)
}

type SecretBackendRoleVhostState struct {
	Configure string `pulumi:"configure"`
	Host      string `pulumi:"host"`
	Read      string `pulumi:"read"`
	Write     string `pulumi:"write"`
}

type SecretBackendRoleVhostStateInput interface {
	pulumi.Input

	ToSecretBackendRoleVhostStateOutput() SecretBackendRoleVhostStateOutput
	ToSecretBackendRoleVhostStateOutputWithContext(context.Context) SecretBackendRoleVhostStateOutput
}

type SecretBackendRoleVhostStateArgs struct {
	Configure pulumi.StringInput `pulumi:"configure"`
	Host      pulumi.StringInput `pulumi:"host"`
	Read      pulumi.StringInput `pulumi:"read"`
	Write     pulumi.StringInput `pulumi:"write"`
}

func (SecretBackendRoleVhostStateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretBackendRoleVhostState)(nil)).Elem()
}

func (i SecretBackendRoleVhostStateArgs) ToSecretBackendRoleVhostStateOutput() SecretBackendRoleVhostStateOutput {
	return i.ToSecretBackendRoleVhostStateOutputWithContext(context.Background())
}

func (i SecretBackendRoleVhostStateArgs) ToSecretBackendRoleVhostStateOutputWithContext(ctx context.Context) SecretBackendRoleVhostStateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretBackendRoleVhostStateOutput)
}

type SecretBackendRoleVhostStateArrayInput interface {
	pulumi.Input

	ToSecretBackendRoleVhostStateArrayOutput() SecretBackendRoleVhostStateArrayOutput
	ToSecretBackendRoleVhostStateArrayOutputWithContext(context.Context) SecretBackendRoleVhostStateArrayOutput
}

type SecretBackendRoleVhostStateArray []SecretBackendRoleVhostStateInput

func (SecretBackendRoleVhostStateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SecretBackendRoleVhostState)(nil)).Elem()
}

func (i SecretBackendRoleVhostStateArray) ToSecretBackendRoleVhostStateArrayOutput() SecretBackendRoleVhostStateArrayOutput {
	return i.ToSecretBackendRoleVhostStateArrayOutputWithContext(context.Background())
}

func (i SecretBackendRoleVhostStateArray) ToSecretBackendRoleVhostStateArrayOutputWithContext(ctx context.Context) SecretBackendRoleVhostStateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretBackendRoleVhostStateArrayOutput)
}

type SecretBackendRoleVhostStateOutput struct{ *pulumi.OutputState }

func (SecretBackendRoleVhostStateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SecretBackendRoleVhostState)(nil)).Elem()
}

func (o SecretBackendRoleVhostStateOutput) ToSecretBackendRoleVhostStateOutput() SecretBackendRoleVhostStateOutput {
	return o
}

func (o SecretBackendRoleVhostStateOutput) ToSecretBackendRoleVhostStateOutputWithContext(ctx context.Context) SecretBackendRoleVhostStateOutput {
	return o
}

func (o SecretBackendRoleVhostStateOutput) Configure() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhostState) string { return v.Configure }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostStateOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhostState) string { return v.Host }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostStateOutput) Read() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhostState) string { return v.Read }).(pulumi.StringOutput)
}

func (o SecretBackendRoleVhostStateOutput) Write() pulumi.StringOutput {
	return o.ApplyT(func(v SecretBackendRoleVhostState) string { return v.Write }).(pulumi.StringOutput)
}

type SecretBackendRoleVhostStateArrayOutput struct{ *pulumi.OutputState }

func (SecretBackendRoleVhostStateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SecretBackendRoleVhostState)(nil)).Elem()
}

func (o SecretBackendRoleVhostStateArrayOutput) ToSecretBackendRoleVhostStateArrayOutput() SecretBackendRoleVhostStateArrayOutput {
	return o
}

func (o SecretBackendRoleVhostStateArrayOutput) ToSecretBackendRoleVhostStateArrayOutputWithContext(ctx context.Context) SecretBackendRoleVhostStateArrayOutput {
	return o
}

func (o SecretBackendRoleVhostStateArrayOutput) Index(i pulumi.IntInput) SecretBackendRoleVhostStateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) SecretBackendRoleVhostState {
		return vs[0].([]SecretBackendRoleVhostState)[vs[1].(int)]
	}).(SecretBackendRoleVhostStateOutput)
}

func init() {
	pulumi.RegisterOutputType(SecretBackendRoleVhostOutput{})
	pulumi.RegisterOutputType(SecretBackendRoleVhostArrayOutput{})
	pulumi.RegisterOutputType(SecretBackendRoleVhostArgsOutput{})
	pulumi.RegisterOutputType(SecretBackendRoleVhostArgsArrayOutput{})
	pulumi.RegisterOutputType(SecretBackendRoleVhostStateOutput{})
	pulumi.RegisterOutputType(SecretBackendRoleVhostStateArrayOutput{})
}
