// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AuthBackendTune {
    allowedResponseHeaders?: pulumi.Input<pulumi.Input<string>[]>;
    auditNonHmacRequestKeys?: pulumi.Input<pulumi.Input<string>[]>;
    auditNonHmacResponseKeys?: pulumi.Input<pulumi.Input<string>[]>;
    defaultLeaseTtl?: pulumi.Input<string>;
    /**
     * Speficies whether to show this mount in the UI-specific listing endpoint.
     */
    listingVisibility?: pulumi.Input<string>;
    maxLeaseTtl?: pulumi.Input<string>;
    passthroughRequestHeaders?: pulumi.Input<pulumi.Input<string>[]>;
    tokenType?: pulumi.Input<string>;
}

export interface GetPolicyDocumentRule {
    /**
     * Whitelists a list of keys and values that are permitted on the given path. See Parameters below.
     */
    allowedParameters?: outputs.GetPolicyDocumentRuleAllowedParameter[];
    /**
     * A list of capabilities that this rule apply to `path`. For example, ["read", "write"].
     */
    capabilities: string[];
    /**
     * Blacklists a list of parameter and values. Any values specified here take precedence over `allowedParameter`. See Parameters below.
     */
    deniedParameters?: outputs.GetPolicyDocumentRuleDeniedParameter[];
    /**
     * Description of the rule. Will be added as a commend to rendered rule.
     */
    description?: string;
    /**
     * The maximum allowed TTL that clients can specify for a wrapped response.
     */
    maxWrappingTtl?: string;
    /**
     * The minimum allowed TTL that clients can specify for a wrapped response.
     */
    minWrappingTtl?: string;
    /**
     * A path in Vault that this rule applies to.
     */
    path: string;
    /**
     * A list of parameters that must be specified.
     */
    requiredParameters?: string[];
}

export interface GetPolicyDocumentRuleAllowedParameter {
    /**
     * name of permitted or denied parameter.
     */
    key: string;
    /**
     * list of values what are permitted or denied by policy rule.
     */
    values: string[];
}

export interface GetPolicyDocumentRuleDeniedParameter {
    /**
     * name of permitted or denied parameter.
     */
    key: string;
    /**
     * list of values what are permitted or denied by policy rule.
     */
    values: string[];
}

export interface ProviderAuthLogin {
    namespace?: pulumi.Input<string>;
    parameters?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    path: pulumi.Input<string>;
}

export interface ProviderClientAuth {
    certFile: pulumi.Input<string>;
    keyFile: pulumi.Input<string>;
}
export namespace azure {
    export interface BackendRoleAzureRole {
        roleId?: pulumi.Input<string>;
        roleName: pulumi.Input<string>;
        scope: pulumi.Input<string>;
    }
}

export namespace config {
    export interface AuthLogins {
        namespace?: pulumi.Input<string>;
        parameters?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        path: pulumi.Input<string>;
    }

    export interface ClientAuths {
        certFile: pulumi.Input<string>;
        keyFile: pulumi.Input<string>;
    }
}

export namespace database {
    export interface SecretBackendConnectionCassandra {
        connectTimeout?: pulumi.Input<number>;
        hosts?: pulumi.Input<pulumi.Input<string>[]>;
        insecureTls?: pulumi.Input<boolean>;
        password?: pulumi.Input<string>;
        pemBundle?: pulumi.Input<string>;
        pemJson?: pulumi.Input<string>;
        port?: pulumi.Input<number>;
        protocolVersion?: pulumi.Input<number>;
        tls?: pulumi.Input<boolean>;
        username?: pulumi.Input<string>;
    }

    export interface SecretBackendConnectionHana {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }

    export interface SecretBackendConnectionMongodb {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }

    export interface SecretBackendConnectionMssql {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }

    export interface SecretBackendConnectionMysql {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }

    export interface SecretBackendConnectionMysqlAurora {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }

    export interface SecretBackendConnectionMysqlLegacy {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }

    export interface SecretBackendConnectionMysqlRds {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }

    export interface SecretBackendConnectionOracle {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }

    export interface SecretBackendConnectionPostgresql {
        connectionUrl?: pulumi.Input<string>;
        maxConnectionLifetime?: pulumi.Input<number>;
        maxIdleConnections?: pulumi.Input<number>;
        maxOpenConnections?: pulumi.Input<number>;
    }
}

export namespace gcp {
    export interface SecretRolesetBinding {
        resource: pulumi.Input<string>;
        roles: pulumi.Input<pulumi.Input<string>[]>;
    }
}

export namespace github {
    export interface AuthBackendTune {
        allowedResponseHeaders?: pulumi.Input<pulumi.Input<string>[]>;
        auditNonHmacRequestKeys?: pulumi.Input<pulumi.Input<string>[]>;
        auditNonHmacResponseKeys?: pulumi.Input<pulumi.Input<string>[]>;
        defaultLeaseTtl?: pulumi.Input<string>;
        listingVisibility?: pulumi.Input<string>;
        maxLeaseTtl?: pulumi.Input<string>;
        passthroughRequestHeaders?: pulumi.Input<pulumi.Input<string>[]>;
        /**
         * (Optional) The type of token that should be generated. Can be `service`,
         * `batch`, or `default` to use the mount's tuned default (which unless changed will be
         * `service` tokens). For token store roles, there are two additional possibilities:
         * `default-service` and `default-batch` which specify the type to return unless the client
         * requests a different type at generation time.
         */
        tokenType?: pulumi.Input<string>;
    }
}

export namespace identity {
    export interface GetEntityAlias {
        canonicalId: string;
        creationTime: string;
        id: string;
        lastUpdateTime: string;
        mergedFromCanonicalIds: string[];
        metadata: {[key: string]: any};
        mountAccessor: string;
        mountPath: string;
        mountType: string;
        name: string;
    }
}

export namespace jwt {
    export interface AuthBackendTune {
        allowedResponseHeaders?: pulumi.Input<pulumi.Input<string>[]>;
        auditNonHmacRequestKeys?: pulumi.Input<pulumi.Input<string>[]>;
        auditNonHmacResponseKeys?: pulumi.Input<pulumi.Input<string>[]>;
        defaultLeaseTtl?: pulumi.Input<string>;
        listingVisibility?: pulumi.Input<string>;
        maxLeaseTtl?: pulumi.Input<string>;
        passthroughRequestHeaders?: pulumi.Input<pulumi.Input<string>[]>;
        tokenType?: pulumi.Input<string>;
    }
}

export namespace okta {
    export interface AuthBackendGroup {
        groupName: pulumi.Input<string>;
        policies: pulumi.Input<pulumi.Input<string>[]>;
    }

    export interface AuthBackendUser {
        groups: pulumi.Input<pulumi.Input<string>[]>;
        policies?: pulumi.Input<pulumi.Input<string>[]>;
        username: pulumi.Input<string>;
    }
}

export namespace rabbitMq {
    export interface SecretBackendRoleVhost {
        configure: pulumi.Input<string>;
        host: pulumi.Input<string>;
        read: pulumi.Input<string>;
        write: pulumi.Input<string>;
    }
}

