// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Vault.Aws
{
    public partial class SecretBackendRole : Pulumi.CustomResource
    {
        /// <summary>
        /// The path of the AWS Secret Backend the role belongs to.
        /// </summary>
        [Output("backend")]
        public Output<string> Backend { get; private set; } = null!;

        /// <summary>
        /// Role credential type.
        /// </summary>
        [Output("credentialType")]
        public Output<string> CredentialType { get; private set; } = null!;

        /// <summary>
        /// The default TTL in seconds for STS credentials. When a TTL is not specified when STS credentials are
        /// requested, and a default TTL is specified on the role, then this default TTL will be used. Valid only when
        /// credential_type is one of assumed_role or federation_token.
        /// </summary>
        [Output("defaultStsTtl")]
        public Output<int> DefaultStsTtl { get; private set; } = null!;

        /// <summary>
        /// The max allowed TTL in seconds for STS credentials (credentials TTL are capped to max_sts_ttl). Valid only
        /// when credential_type is one of assumed_role or federation_token.
        /// </summary>
        [Output("maxStsTtl")]
        public Output<int> MaxStsTtl { get; private set; } = null!;

        /// <summary>
        /// Unique name for the role.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// ARN for an existing IAM policy the role should use.
        /// </summary>
        [Output("policyArns")]
        public Output<ImmutableArray<string>> PolicyArns { get; private set; } = null!;

        /// <summary>
        /// IAM policy the role should use in JSON format.
        /// </summary>
        [Output("policyDocument")]
        public Output<string?> PolicyDocument { get; private set; } = null!;

        /// <summary>
        /// ARNs of AWS roles allowed to be assumed. Only valid when credential_type is 'assumed_role'
        /// </summary>
        [Output("roleArns")]
        public Output<ImmutableArray<string>> RoleArns { get; private set; } = null!;


        /// <summary>
        /// Create a SecretBackendRole resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SecretBackendRole(string name, SecretBackendRoleArgs args, CustomResourceOptions? options = null)
            : base("vault:aws/secretBackendRole:SecretBackendRole", name, args ?? ResourceArgs.Empty, MakeResourceOptions(options, ""))
        {
        }

        private SecretBackendRole(string name, Input<string> id, SecretBackendRoleState? state = null, CustomResourceOptions? options = null)
            : base("vault:aws/secretBackendRole:SecretBackendRole", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SecretBackendRole resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SecretBackendRole Get(string name, Input<string> id, SecretBackendRoleState? state = null, CustomResourceOptions? options = null)
        {
            return new SecretBackendRole(name, id, state, options);
        }
    }

    public sealed class SecretBackendRoleArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The path of the AWS Secret Backend the role belongs to.
        /// </summary>
        [Input("backend", required: true)]
        public Input<string> Backend { get; set; } = null!;

        /// <summary>
        /// Role credential type.
        /// </summary>
        [Input("credentialType", required: true)]
        public Input<string> CredentialType { get; set; } = null!;

        /// <summary>
        /// The default TTL in seconds for STS credentials. When a TTL is not specified when STS credentials are
        /// requested, and a default TTL is specified on the role, then this default TTL will be used. Valid only when
        /// credential_type is one of assumed_role or federation_token.
        /// </summary>
        [Input("defaultStsTtl")]
        public Input<int>? DefaultStsTtl { get; set; }

        /// <summary>
        /// The max allowed TTL in seconds for STS credentials (credentials TTL are capped to max_sts_ttl). Valid only
        /// when credential_type is one of assumed_role or federation_token.
        /// </summary>
        [Input("maxStsTtl")]
        public Input<int>? MaxStsTtl { get; set; }

        /// <summary>
        /// Unique name for the role.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("policyArns")]
        private InputList<string>? _policyArns;

        /// <summary>
        /// ARN for an existing IAM policy the role should use.
        /// </summary>
        public InputList<string> PolicyArns
        {
            get => _policyArns ?? (_policyArns = new InputList<string>());
            set => _policyArns = value;
        }

        /// <summary>
        /// IAM policy the role should use in JSON format.
        /// </summary>
        [Input("policyDocument")]
        public Input<string>? PolicyDocument { get; set; }

        [Input("roleArns")]
        private InputList<string>? _roleArns;

        /// <summary>
        /// ARNs of AWS roles allowed to be assumed. Only valid when credential_type is 'assumed_role'
        /// </summary>
        public InputList<string> RoleArns
        {
            get => _roleArns ?? (_roleArns = new InputList<string>());
            set => _roleArns = value;
        }

        public SecretBackendRoleArgs()
        {
        }
    }

    public sealed class SecretBackendRoleState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The path of the AWS Secret Backend the role belongs to.
        /// </summary>
        [Input("backend")]
        public Input<string>? Backend { get; set; }

        /// <summary>
        /// Role credential type.
        /// </summary>
        [Input("credentialType")]
        public Input<string>? CredentialType { get; set; }

        /// <summary>
        /// The default TTL in seconds for STS credentials. When a TTL is not specified when STS credentials are
        /// requested, and a default TTL is specified on the role, then this default TTL will be used. Valid only when
        /// credential_type is one of assumed_role or federation_token.
        /// </summary>
        [Input("defaultStsTtl")]
        public Input<int>? DefaultStsTtl { get; set; }

        /// <summary>
        /// The max allowed TTL in seconds for STS credentials (credentials TTL are capped to max_sts_ttl). Valid only
        /// when credential_type is one of assumed_role or federation_token.
        /// </summary>
        [Input("maxStsTtl")]
        public Input<int>? MaxStsTtl { get; set; }

        /// <summary>
        /// Unique name for the role.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("policyArns")]
        private InputList<string>? _policyArns;

        /// <summary>
        /// ARN for an existing IAM policy the role should use.
        /// </summary>
        public InputList<string> PolicyArns
        {
            get => _policyArns ?? (_policyArns = new InputList<string>());
            set => _policyArns = value;
        }

        /// <summary>
        /// IAM policy the role should use in JSON format.
        /// </summary>
        [Input("policyDocument")]
        public Input<string>? PolicyDocument { get; set; }

        [Input("roleArns")]
        private InputList<string>? _roleArns;

        /// <summary>
        /// ARNs of AWS roles allowed to be assumed. Only valid when credential_type is 'assumed_role'
        /// </summary>
        public InputList<string> RoleArns
        {
            get => _roleArns ?? (_roleArns = new InputList<string>());
            set => _roleArns = value;
        }

        public SecretBackendRoleState()
        {
        }
    }
}
