// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getAuthBackendRoleId(args: GetAuthBackendRoleIdArgs, opts?: pulumi.InvokeOptions): Promise<GetAuthBackendRoleIdResult> & GetAuthBackendRoleIdResult {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    const promise: Promise<GetAuthBackendRoleIdResult> = pulumi.runtime.invoke("vault:appRole/getAuthBackendRoleId:getAuthBackendRoleId", {
        "backend": args.backend,
        "roleName": args.roleName,
    }, opts);

    return pulumi.utils.liftProperties(promise, opts);
}

/**
 * A collection of arguments for invoking getAuthBackendRoleId.
 */
export interface GetAuthBackendRoleIdArgs {
    readonly backend?: string;
    readonly roleName: string;
}

/**
 * A collection of values returned by getAuthBackendRoleId.
 */
export interface GetAuthBackendRoleIdResult {
    readonly backend?: string;
    readonly roleId: string;
    readonly roleName: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
